id: I8BF72712
ocr_import_info:
  source: bdrc
  software: google_books
  batch: batch_2022
  expected_default_language: bo
  bdrc_scan_id: W2CZ7900
  ocr_info:
    timestamp: 11/17/22T20:55:49
    html: html.zip
    txt: txt.zip
    images: images.zip
  op_import_options: {}
  op_import_version: 0.11.9
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2024-02-28 15:00:19.068907+00:00
last_modified: 2024-02-28 15:00:19.068915+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W2CZ7900
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2CZ7900
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཕར་ཕྱིན་སྤྱི་དོན།
  languages:
  - bo
  author: ཁྲི ༢༢་དགེ་འདུན་བསྟན་པ་དར་རྒྱས།
statistics:
  ocr_word_mean_confidence_index: 0.628007572442398
  ocr_word_median_confidence_index: 0.65
bases:
  I1KG10539:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10539
      total_pages: 766
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG10539.txt
    statistics:
      ocr_word_median_confidence_index: 0.65
      ocr_word_mean_confidence_index: 0.628007572442398
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
